/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Hotel.Contrato;
import Hotel.Hóspede;
import Hotel.Serviços;
import buffers.BufferContrato;
import fileModel.Arquivos;
import java.io.File;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme A. F. Leite, Matrícula: 161080022
 */
public class EditarServiços extends javax.swing.JDialog {
    Arquivos arq;
    Arquivos arqc;
    List<String> lista;
    List<String> listac;
    private File arquivo;
    private File arquivoc;
    Serviços s=null;
    Contrato c = null;
    /**
     * Creates new form EditarContratos
     */
    public EditarServiços(java.awt.Frame parent, boolean modal, Serviços servico) {
        super(parent, modal);
        initComponents();
        
        arq = new Arquivos("servicos");
        arquivo = arq.getFile();
        lista = arq.lerArquivo(arquivo);
        s=servico;
        ///////////
        arqc = new Arquivos("contratos");
        arquivoc = arqc.getFile();
        listac = arqc.lerArquivo(arquivoc);
        //h = new Hóspede(0);
        preencher();
        hospedePreencher();
        limpar();
        desabilitarCampos();        
        
    }
    
    public EditarServiços(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        arq = new Arquivos("contratos");
        arquivo = arq.getFile();
        lista = arq.lerArquivo(arquivo);
        
        ///////////
        arqc = new Arquivos("hospedes");
        arquivoc = arqc.getFile();
        listac = arqc.lerArquivo(arquivoc);
        s = new Serviços();
        c = s.getC();
        c.setS(s);
        
        preencher();
        hospedePreencher();
        limpar();
        desabilitarCampos();        
        
    }
    
    private void hospedePreencher(){
        File f = arqc.getFile();
        listac = arqc.lerArquivo(f);
        DefaultTableModel model = (DefaultTableModel) tabelaContratos.getModel();
        model.setRowCount(0);
        int t = 0;
        while (t < listac.size()) {
            model.addRow(listac.get(t).split(";"));
            t++;
        }
    }
    
    private void limpar() {
        idCampo.setText("");
        idContratoCampo.setText("");
        idServicoCampo.setText("");
        textoCampo.setText("");
    }
    
    private void desabilitarCampos(){
        listaServiços.setEnabled(false);
        textoCampo.setEditable(false);
    }
    
    private void habilitarCampos(){
        listaServiços.setEnabled(true);
        textoCampo.setEditable(true);
    }
    
    private void preencher() {
        File f = arq.getFile();
        lista = arq.lerArquivo(f);
        DefaultTableModel model = (DefaultTableModel) tabelaServiços.getModel();
        model.setRowCount(0);
        int t = 0;
        while (t < lista.size()) {
            model.addRow(lista.get(t).split(";"));
            t++;
        }
        
    }
    
    private boolean camposVazios() {
        boolean b = true;
        if (textoCampo.getText().equals("null") || textoCampo.getText().equals("")) {
            b = false;
        }
        return b;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoGrupal = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idCampo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idContratoCampo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idServicoCampo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaServiços = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textoCampo = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServiços = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaContratos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 55, 58));

        jPanel4.setBackground(new java.awt.Color(76, 82, 86));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)), "Edição de Serviços", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(51, 55, 58));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)), "Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID: ");
        jLabel1.setToolTipText("ID de Cadastro do Hóspede");

        idCampo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        idCampo.setForeground(new java.awt.Color(255, 255, 255));
        idCampo.setText("000");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/service1.png"))); // NOI18N

        idContratoCampo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        idContratoCampo.setForeground(new java.awt.Color(255, 255, 255));
        idContratoCampo.setText("000");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CA:");
        jLabel2.setToolTipText("ID do Contrato Atual: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SA:");
        jLabel5.setToolTipText("ID do Contrato Atual: ");

        idServicoCampo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        idServicoCampo.setForeground(new java.awt.Color(255, 255, 255));
        idServicoCampo.setText("000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idCampo))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idContratoCampo))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idServicoCampo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idCampo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idContratoCampo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idServicoCampo))
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(51, 55, 58));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)), "Hóspede", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane5.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane5.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        listaServiços.setAutoCreateRowSorter(true);
        listaServiços.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        listaServiços.setForeground(new java.awt.Color(0, 0, 0));
        listaServiços.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serviços"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaServiços.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaServiçosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(listaServiços);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel8.setBackground(new java.awt.Color(51, 55, 58));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)), "Dados do Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane4.setViewportView(textoCampo);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(51, 55, 58));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));

        exitButton.setBackground(new java.awt.Color(51, 51, 51));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leave.png"))); // NOI18N
        exitButton.setToolTipText("Sair");
        exitButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leave1.gif"))); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(51, 51, 51));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save1.png"))); // NOI18N
        saveButton.setToolTipText("Salvar");
        saveButton.setEnabled(false);
        saveButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(51, 51, 51));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        editButton.setToolTipText("Editar Dados");
        editButton.setEnabled(false);
        editButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password1.gif"))); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(51, 51, 51));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel1.png"))); // NOI18N
        cancelButton.setToolTipText("Cancelar");
        cancelButton.setEnabled(false);
        cancelButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel2.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton)
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addGap(18, 18, 18)
                .addComponent(exitButton)
                .addGap(171, 171, 171))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelButton)
                    .addComponent(saveButton)
                    .addComponent(exitButton)
                    .addComponent(editButton))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(76, 82, 86));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelaServiços.setAutoCreateRowSorter(true);
        tabelaServiços.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tabelaServiços.setForeground(new java.awt.Color(0, 0, 0));
        tabelaServiços.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "Serviços"}
            },
            new String [] {
                "ID", "Serviços"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaServiços.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaServiçosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaServiços);

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelaContratos.setAutoCreateRowSorter(true);
        tabelaContratos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tabelaContratos.setForeground(new java.awt.Color(0, 0, 0));
        tabelaContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "Aberto", "5", "João", "01/01/2000", "31/12/2018", "000011112222", "25", "aaaaaaaaaa", "001"}
            },
            new String [] {
                "ID", "Status", "ID do Hóspede", "Nome do Hóspede", "Data Inicial", "Data Final", "Cartão", "Tarifa", "Qtd. de Serviços", "ID de Serviço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaContratosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaContratos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        /*
        File arquivo = arq.getFile();
        lista = arq.lerArquivo(arquivo);
        String idH = idCampo.getText();
        String idC = idContratoCampo.getText();
        String idS = idServicoCampo.getText();
        String nome = nomeCampo.getText();
        //String cpf = cpfCampo.getText();
        String status = statusCampo.getText();
        String dataInicial = dataInicialCampo.getText();
        String dataFinal = dataFinalCampo.getText();
        String validadeCartao = validadeCartaoCampo.getText();
        String cartaoNum = cartaoCampo.getText();
        String bandeiraCartao = bandeiraCartaoCampo.getText();
        String tarifaTipo = tipoTarifaCampo.getText();
        String qtdServicos = qtdServicoCampo.getText();


        if (!camposVazios()) {
            JOptionPane.showMessageDialog(this, "Impossível salvar!\nHá campos vazios", "Falha", JOptionPane.ERROR_MESSAGE);
            limpar();
        } else {
            //String idCliente = idCampo.getText();
            String contratoEditado =""+ idC + ";" + status+ ";" + idH +";"
            +  nome+ ";" + dataInicial+ ";" + dataFinal + ";"
            + cartaoNum + "|"+ bandeiraCartao + "|"+ validadeCartao + ";"
            + tarifaTipo + ";"  + qtdServicos + ";"
            + idS;

            lista = BufferContrato.editarContrato(lista, idC, contratoEditado);
            if (arq.regravarDados(arquivo, lista)) {
                JOptionPane.showMessageDialog(this, "Editado", "Edição Salva", JOptionPane.INFORMATION_MESSAGE);
                preencher();
                hospedePreencher();
                limpar();
                desabilitarCampos();
                cancelButton.setEnabled(false);
                saveButton.setEnabled(false);
                serviceButton.setEnabled(false);
                checkoutButton.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Falha", "Edição Não salva", JOptionPane.ERROR_MESSAGE);
                preencher();
                hospedePreencher();
                limpar();
                desabilitarCampos();
                cancelButton.setEnabled(false);
                saveButton.setEnabled(false);
                serviceButton.setEnabled(false);
                checkoutButton.setEnabled(false);
            }
        }
        preencher();
        hospedePreencher();
        limpar();
        */
    }//GEN-LAST:event_saveButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        /*
        
        habilitarCampos();
        saveButton.setEnabled(true);
        cancelButton.setEnabled(true);
        serviceButton.setEnabled(false);
        editButton.setEnabled(false);
        checkoutButton.setEnabled(false);
        */
    }//GEN-LAST:event_editButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        //id--;
        cancelButton.setEnabled(false);

        
        saveButton.setEnabled(false);
        editButton.setEnabled(false);
        //checkoutButton.setEnabled(false);
        limpar();
        desabilitarCampos();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void tabelaContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaContratosMouseClicked
        /*// TODO add your handling code here:
        String[] ca;
        hospedePreencher();
        checkoutButton.setEnabled(true);
        editButton.setEnabled(true);
        serviceButton.setEnabled(true);
        int linha=tabelaContratos.getSelectedRow();

        hospedePreencher();
        idCampo.setText(tabelaContratos.getValueAt(linha, 2).toString());
        nomeCampo.setText(tabelaContratos.getValueAt(linha, 3).toString());
        idContratoCampo.setText(tabelaContratos.getValueAt(linha, 0).toString());
        idServicoCampo.setText(tabelaContratos.getValueAt(linha, 9).toString());

        String idh = idCampo.getText();
        int parsed = Integer.parseInt(idh);
        tabelaUsuarios.setRowSelectionInterval(parsed, parsed);
        int linha1 = tabelaUsuarios.getSelectedRow();
        //System.out.println(""+idh);

        if(tabelaUsuarios.getValueAt(linha1, 6) == null){
            cpfCampo.setText("null");

        }else{
            cpfCampo.setText(tabelaUsuarios.getValueAt(linha1, 6).toString());
        }
        if(tabelaUsuarios.getValueAt(linha1, 9)== null){
            nascimentoCampo.setText("null");
        }else{
            nascimentoCampo.setText(tabelaUsuarios.getValueAt(linha1, 9).toString());
        }

        if(tabelaUsuarios.getValueAt(linha1, 2) != null){
            if ((tabelaUsuarios.getValueAt(linha1, 2).toString()).charAt(0) == 'F') {
                femininoJButton.setSelected(true);
            } else {
                masculinoJButton.setSelected(true);
            }
        }else{
            femininoJButton.setSelected(true);
            masculinoJButton.setSelected(true);
        }
        statusCampo.setText(tabelaContratos.getValueAt(linha, 1).toString());
        if(tabelaContratos.getValueAt(linha, 6).toString().equalsIgnoreCase("||")){
            cartaoCampo.setText("null");
            bandeiraCartaoCampo.setText("null");
            validadeCartaoCampo.setText("null");
        }else {
            String cartao =tabelaContratos.getValueAt(linha, 6).toString();

            ca = cartao.split("\\|");
            System.out.println(""+Arrays.toString(ca));
            cartaoCampo.setText(ca[0]);
            bandeiraCartaoCampo.setText(ca[1]);
            validadeCartaoCampo.setText(ca[2]);
        }

        dataInicialCampo.setText(tabelaContratos.getValueAt(linha, 4).toString());
        dataFinalCampo.setText(tabelaContratos.getValueAt(linha, 5).toString());
        tipoTarifaCampo.setText(tabelaContratos.getValueAt(linha, 7).toString());
        qtdServicoCampo.setText(tabelaContratos.getValueAt(linha, 8).toString());
        hospedePreencher();
        preencher();

        //int linha1 = tabelaUsuarios.getSelectedRow();*/
    }//GEN-LAST:event_tabelaContratosMouseClicked

    private void tabelaServiçosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaServiçosMouseClicked
        // TODO add your handling code here:
        File f = arq.getFile();
        lista = arq.lerArquivo(f);
        editButton.setEnabled(true);
        int linha=tabelaServiços.getSelectedRow();
        //ListModel model = listaServiços.getModel();
        /*DefaultTableModel model = (DefaultTableModel) listaServiços.getModel();
        model.setRowCount(0);
        int t = 0;
        while (t < lista.size()) {
            model.addColumn(lista.get(t).split("\\;"));
            //model.addRow(os);
            t++;
        }
        */
        //File f = arq.getFile();
        //lista = arq.lerArquivo(f);
        DefaultTableModel model = (DefaultTableModel) listaServiços.getModel();
        model.setRowCount(0);
        
        
        String s= tabelaServiços.getValueAt(linha, 1).toString();
        for(String a : s.split("\\;")){
            model.addRow(a.split("\\|"));
            
        }
        habilitarCampos();
        //int x = listaServiços.getSelectedRow();                
        
        
    }//GEN-LAST:event_tabelaServiçosMouseClicked

    private void listaServiçosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaServiçosMouseClicked
        // TODO add your handling code here:
        String[] ca;
        int linha = listaServiços.getSelectedRow();
        textoCampo.setText(listaServiços.getValueAt(linha, 0).toString());
    }//GEN-LAST:event_listaServiçosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarServiços.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarServiços.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarServiços.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarServiços.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarServiços dialog = new EditarServiços(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel idCampo;
    private javax.swing.JLabel idContratoCampo;
    private javax.swing.JLabel idServicoCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable listaServiços;
    private javax.swing.JButton saveButton;
    private javax.swing.ButtonGroup sexoGrupal;
    private javax.swing.JTable tabelaContratos;
    private javax.swing.JTable tabelaServiços;
    private javax.swing.JTextPane textoCampo;
    // End of variables declaration//GEN-END:variables
}
