/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Hotel.Hóspede;
import buffers.BufferContrato;
import fileModel.Arquivos;
import buffers.BufferHóspede;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;






/**
 *
 * @author Guilherme A. F. Leite, Matrícula: 161080022
 */
public class Inicial extends javax.swing.JFrame {
    Arquivos arq;
    Arquivos arq1;
    Arquivos arq2;
    List<String> lista;
    static int trial = 0;
    long start = System.currentTimeMillis();
   
    private static Inicial janela;
    
    public Inicial(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        arq = new Arquivos("hospedes");
        arq1 = new Arquivos("contratos");
        arq2 = new Arquivos("servicos");
        preencher();
        preencher1();
        preencher2();
    }
    static{
        janela = new Inicial(null, true);
    }
    public static Inicial getInstance(){
        return janela;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        HóspedesPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        deleteButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        idCampo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ContratosPanel = new javax.swing.JPanel();
        exitButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaContratos = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        deleteButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomeCampo1 = new javax.swing.JTextField();
        editButton1 = new javax.swing.JButton();
        addButton1 = new javax.swing.JButton();
        idContratoCampo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        abertoToggle = new javax.swing.JToggleButton();
        fechadoToggle = new javax.swing.JToggleButton();
        ServiçosPanel = new javax.swing.JPanel();
        exitButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaServiços = new javax.swing.JTable();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        deleteButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nomeCampo2 = new javax.swing.JTextField();
        editButton2 = new javax.swing.JButton();
        addButton2 = new javax.swing.JButton();
        idContratoCampo1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        QuartosPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ArquivoMenu = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        ExibirMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        AdminMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        AjudaMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(76, 82, 86));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hotel1.gif"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HOTEL CAMPINA COMFORT PREMIUM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(76, 82, 86));

        jTabbedPane1.setBackground(new java.awt.Color(76, 82, 86));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setOpaque(true);

        HóspedesPanel.setBackground(new java.awt.Color(51, 55, 58));
        HóspedesPanel.setForeground(new java.awt.Color(255, 255, 255));
        HóspedesPanel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N

        exitButton.setBackground(new java.awt.Color(51, 51, 51));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leave.png"))); // NOI18N
        exitButton.setToolTipText("Sair");
        exitButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leave1.gif"))); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseEntered(evt);
            }
        });

        tabelaUsuarios.setAutoCreateRowSorter(true);
        tabelaUsuarios.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tabelaUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "João", "M", "99 99999-9999", "aaa@gmail.com", "0000000", "00000000099", "aaaa", "vvvvv", "01/01/2000", "31/12/2018", "999"}
            },
            new String [] {
                "ID", "Nome", "Sexo", "Telefone", "Email", "RG", "CPF", "Endereço", "Endereço 2", "Data de Nascimento", "Data de Cadastro", "Contrato nº"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaUsuarios);

        deleteButton.setBackground(new java.awt.Color(51, 51, 51));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/X1.png"))); // NOI18N
        deleteButton.setToolTipText("Remover Hóspede");
        deleteButton.setEnabled(false);
        deleteButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/X2.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID: ");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        nomeCampo.setEditable(false);
        nomeCampo.setBackground(new java.awt.Color(51, 51, 51));
        nomeCampo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nomeCampo.setForeground(new java.awt.Color(255, 255, 255));
        nomeCampo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        editButton.setBackground(new java.awt.Color(51, 51, 51));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        editButton.setToolTipText("Editar Dados");
        editButton.setEnabled(false);
        editButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password1.gif"))); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(51, 51, 51));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newuser.gif"))); // NOI18N
        addButton.setToolTipText("Novo Hóspede");
        addButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newuser1.gif"))); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        idCampo.setBackground(new java.awt.Color(51, 51, 51));
        idCampo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        idCampo.setForeground(new java.awt.Color(255, 255, 255));
        idCampo.setText("000");

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome:");

        javax.swing.GroupLayout HóspedesPanelLayout = new javax.swing.GroupLayout(HóspedesPanel);
        HóspedesPanel.setLayout(HóspedesPanelLayout);
        HóspedesPanelLayout.setHorizontalGroup(
            HóspedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HóspedesPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(HóspedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HóspedesPanelLayout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(184, 184, 184)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editButton)
                        .addGap(183, 183, 183)
                        .addComponent(exitButton))
                    .addComponent(jScrollPane1)
                    .addGroup(HóspedesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HóspedesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        HóspedesPanelLayout.setVerticalGroup(
            HóspedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HóspedesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HóspedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCampo)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HóspedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(exitButton)
                    .addComponent(addButton)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hóspedes", HóspedesPanel);

        ContratosPanel.setBackground(new java.awt.Color(51, 55, 58));
        ContratosPanel.setForeground(new java.awt.Color(255, 255, 255));

        exitButton1.setBackground(new java.awt.Color(51, 51, 51));
        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leave.png"))); // NOI18N
        exitButton1.setToolTipText("Sair");
        exitButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leave1.gif"))); // NOI18N
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseEntered(evt);
            }
        });

        tabelaContratos.setAutoCreateRowSorter(true);
        tabelaContratos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tabelaContratos.setForeground(new java.awt.Color(0, 0, 0));
        tabelaContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "Aberto", "5", "João", "01/01/2000", "31/12/2018", "000011112222", "25", "aaaaaaaaaa", "001"}
            },
            new String [] {
                "ID", "Status", "ID do Hóspede", "Nome do Hóspede", "Data Inicial", "Data Final", "Cartão", "Tarifa", "Qtd. de Serviços", "ID de Serviço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaContratosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaContratos);

        deleteButton1.setBackground(new java.awt.Color(51, 51, 51));
        deleteButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/X1.png"))); // NOI18N
        deleteButton1.setToolTipText("Remover Hóspede");
        deleteButton1.setEnabled(false);
        deleteButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/X2.png"))); // NOI18N
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID: ");

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        nomeCampo1.setEditable(false);
        nomeCampo1.setBackground(new java.awt.Color(51, 51, 51));
        nomeCampo1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nomeCampo1.setForeground(new java.awt.Color(255, 255, 255));
        nomeCampo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        editButton1.setBackground(new java.awt.Color(51, 51, 51));
        editButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        editButton1.setToolTipText("Editar Dados");
        editButton1.setEnabled(false);
        editButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password1.gif"))); // NOI18N
        editButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton1ActionPerformed(evt);
            }
        });

        addButton1.setBackground(new java.awt.Color(51, 51, 51));
        addButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newuser.gif"))); // NOI18N
        addButton1.setToolTipText("Novo Hóspede");
        addButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newuser1.gif"))); // NOI18N
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        idContratoCampo.setBackground(new java.awt.Color(51, 51, 51));
        idContratoCampo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        idContratoCampo.setForeground(new java.awt.Color(255, 255, 255));
        idContratoCampo.setText("000");

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nome do Hóspede");

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ver Contratos: ");

        abertoToggle.setBackground(new java.awt.Color(51, 55, 58));
        abertoToggle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        abertoToggle.setForeground(new java.awt.Color(255, 255, 255));
        abertoToggle.setText("Abertos");
        abertoToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abertoToggleActionPerformed(evt);
            }
        });

        fechadoToggle.setBackground(new java.awt.Color(51, 55, 58));
        fechadoToggle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        fechadoToggle.setForeground(new java.awt.Color(255, 255, 255));
        fechadoToggle.setText("Fechados");
        fechadoToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechadoToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContratosPanelLayout = new javax.swing.GroupLayout(ContratosPanel);
        ContratosPanel.setLayout(ContratosPanelLayout);
        ContratosPanelLayout.setHorizontalGroup(
            ContratosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratosPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(ContratosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContratosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idContratoCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abertoToggle)
                        .addGap(24, 24, 24)
                        .addComponent(fechadoToggle))
                    .addGroup(ContratosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ContratosPanelLayout.createSequentialGroup()
                            .addComponent(addButton1)
                            .addGap(184, 184, 184)
                            .addComponent(deleteButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editButton1)
                            .addGap(183, 183, 183)
                            .addComponent(exitButton1))
                        .addComponent(jScrollPane2)
                        .addGroup(ContratosPanelLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator5)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        ContratosPanelLayout.setVerticalGroup(
            ContratosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContratosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContratosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomeCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idContratoCampo)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(abertoToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechadoToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContratosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(exitButton1)
                    .addComponent(addButton1)
                    .addComponent(deleteButton1)
                    .addComponent(editButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contratos", ContratosPanel);

        ServiçosPanel.setBackground(new java.awt.Color(51, 55, 58));
        ServiçosPanel.setForeground(new java.awt.Color(255, 255, 255));

        exitButton2.setBackground(new java.awt.Color(51, 51, 51));
        exitButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leave.png"))); // NOI18N
        exitButton2.setToolTipText("Sair");
        exitButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leave1.gif"))); // NOI18N
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane3.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseEntered(evt);
            }
        });

        tabelaServiços.setAutoCreateRowSorter(true);
        tabelaServiços.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tabelaServiços.setForeground(new java.awt.Color(0, 0, 0));
        tabelaServiços.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "Serviços"}
            },
            new String [] {
                "ID", "Serviços"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaServiços.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaServiçosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaServiços);

        deleteButton2.setBackground(new java.awt.Color(51, 51, 51));
        deleteButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/X1.png"))); // NOI18N
        deleteButton2.setToolTipText("Remover Hóspede");
        deleteButton2.setEnabled(false);
        deleteButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/X2.png"))); // NOI18N
        deleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton2ActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID: ");

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        nomeCampo2.setEditable(false);
        nomeCampo2.setBackground(new java.awt.Color(51, 51, 51));
        nomeCampo2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nomeCampo2.setForeground(new java.awt.Color(255, 255, 255));
        nomeCampo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        editButton2.setBackground(new java.awt.Color(51, 51, 51));
        editButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        editButton2.setToolTipText("Editar Dados");
        editButton2.setEnabled(false);
        editButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password1.gif"))); // NOI18N
        editButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton2ActionPerformed(evt);
            }
        });

        addButton2.setBackground(new java.awt.Color(51, 51, 51));
        addButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newuser.gif"))); // NOI18N
        addButton2.setToolTipText("Novo Hóspede");
        addButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newuser1.gif"))); // NOI18N
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });

        idContratoCampo1.setBackground(new java.awt.Color(51, 51, 51));
        idContratoCampo1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        idContratoCampo1.setForeground(new java.awt.Color(255, 255, 255));
        idContratoCampo1.setText("000");

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Serviços: ");

        javax.swing.GroupLayout ServiçosPanelLayout = new javax.swing.GroupLayout(ServiçosPanel);
        ServiçosPanel.setLayout(ServiçosPanelLayout);
        ServiçosPanelLayout.setHorizontalGroup(
            ServiçosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiçosPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(ServiçosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ServiçosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idContratoCampo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ServiçosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ServiçosPanelLayout.createSequentialGroup()
                            .addComponent(addButton2)
                            .addGap(184, 184, 184)
                            .addComponent(deleteButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editButton2)
                            .addGap(183, 183, 183)
                            .addComponent(exitButton2))
                        .addComponent(jScrollPane3)
                        .addGroup(ServiçosPanelLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator7)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        ServiçosPanelLayout.setVerticalGroup(
            ServiçosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServiçosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ServiçosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nomeCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idContratoCampo1)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ServiçosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(exitButton2)
                    .addComponent(addButton2)
                    .addComponent(deleteButton2)
                    .addComponent(editButton2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Serviços", ServiçosPanel);

        QuartosPanel.setBackground(new java.awt.Color(51, 55, 58));
        QuartosPanel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout QuartosPanelLayout = new javax.swing.GroupLayout(QuartosPanel);
        QuartosPanel.setLayout(QuartosPanelLayout);
        QuartosPanelLayout.setHorizontalGroup(
            QuartosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
        );
        QuartosPanelLayout.setVerticalGroup(
            QuartosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Quartos", QuartosPanel);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jMenuBar1.setOpaque(false);

        ArquivoMenu.setText("Arquivo");

        jMenuItem10.setText("Novo Usuário");
        ArquivoMenu.add(jMenuItem10);

        jMenuItem11.setText("Novo Hóspede");
        ArquivoMenu.add(jMenuItem11);

        jMenuItem14.setText("Logout");
        ArquivoMenu.add(jMenuItem14);

        jMenuItem15.setText("Sair");
        ArquivoMenu.add(jMenuItem15);

        jMenuBar1.add(ArquivoMenu);

        ExibirMenu.setText("Exibir");

        jMenuItem2.setText("Hóspedes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        ExibirMenu.add(jMenuItem2);

        jMenuItem3.setText("Contratos");
        ExibirMenu.add(jMenuItem3);

        jMenuItem4.setText("Serviços");
        ExibirMenu.add(jMenuItem4);

        jMenuItem5.setText("Quartos");
        ExibirMenu.add(jMenuItem5);

        jMenuItem13.setText("Usuários");
        ExibirMenu.add(jMenuItem13);

        jMenuBar1.add(ExibirMenu);

        AdminMenu.setText("Administrar");

        jMenuItem6.setText("Hóspedes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        AdminMenu.add(jMenuItem6);

        jMenuItem7.setText("Quartos");
        AdminMenu.add(jMenuItem7);

        jMenuItem8.setText("Contratos");
        AdminMenu.add(jMenuItem8);

        jMenuItem9.setText("Serviços");
        AdminMenu.add(jMenuItem9);

        jMenuItem12.setText("Usuários");
        AdminMenu.add(jMenuItem12);

        jMenuBar1.add(AdminMenu);

        AjudaMenu.setText("Ajuda");

        jMenuItem1.setText("Sobre");
        AjudaMenu.add(jMenuItem1);

        jMenuBar1.add(AjudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        preencher();
        preencher1();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void tabelaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuariosMouseClicked
        // TODO add your handling code here:

        // TODO add your handling code here:
        deleteButton.setEnabled(true);
        editButton.setEnabled(true);
        int linha=tabelaUsuarios.getSelectedRow();
        nomeCampo.setText(tabelaUsuarios.getValueAt(linha, 1).toString());
        idCampo.setText(tabelaUsuarios.getValueAt(linha, 0).toString());
        

    }//GEN-LAST:event_tabelaUsuariosMouseClicked

    private void preencher() {
        File f = arq.getFile();
        lista = arq.lerArquivo(f);
        DefaultTableModel model = (DefaultTableModel) tabelaUsuarios.getModel();
        model.setRowCount(0);
        int t = 0;
        while (t < lista.size()) {
            model.addRow(lista.get(t).split(";"));
            t++;
        }
        
    }
    
    
    private void preencher1() {
        File f = arq1.getFile();
        lista = arq1.lerArquivo(f);
        DefaultTableModel model = (DefaultTableModel) tabelaContratos.getModel();
        model.setRowCount(0);
        int t = 0;
        if(abertoToggle.isSelected() && fechadoToggle.isSelected() || (!abertoToggle.isSelected() && !fechadoToggle.isSelected()) ){
        while (t < lista.size()) {
            model.addRow(lista.get(t).split(";"));
            t++;
            }
        }else if(abertoToggle.isSelected()== true && fechadoToggle.isSelected() == false){
            while (t < lista.size()) {
                for(String s: lista.get(t).split(";")){
                    if(s.contains("Aberto")||s.contains("aberto")){
                        model.addRow(lista.get(t).split(";"));
                    }
                }
            t++;            
            }
        }else if(abertoToggle.isSelected()== false && fechadoToggle.isSelected() == true){
            while (t < lista.size()) {
                for(String s: lista.get(t).split(";")){
                    if(s.contains("Fechado")||s.contains("fechado")){
                        model.addRow(lista.get(t).split(";"));
                    }
                }
            t++;            
            }
        }
        
    }
    
    
    private void preencher2() {
        File f = arq2.getFile();
        lista = arq2.lerArquivo(f);
        
        DefaultTableModel model = (DefaultTableModel) tabelaServiços.getModel();
        model.setRowCount(0);
        int t = 0;
        while (t < lista.size()) {
            model.addRow(lista.get(t).split(";"));
            t++;
        }
        
    }
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        File f = arq.getFile();
        lista = arq.lerArquivo(f);

        if (arq.regravarDados(f, BufferHóspede.apagarCliente(lista, idCampo.getText()))) {
            preencher();
            deleteButton.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Hóspede removido.", "Remoção", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Falha na remoção.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        editButton.setEnabled(false);
        
        preencher();
        

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        int linha = tabelaUsuarios.getSelectedRow();
        new EditarHóspede(null,true,0,linha).setVisible(true);
        //Hóspede.setId(idSort(lista));
        //int id = Hóspede.getId();
        //System.out.println(""+id);
        //
        //ABRIR JDIALOG PARA EDIÇÃO
        preencher();
        preencher1();
    }//GEN-LAST:event_editButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:

        new EditarHóspede(null,true,1).setVisible(true);
        //
        //ABRIR JDIALOG PARA ADIÇÃO
        preencher();
        preencher1();
    }//GEN-LAST:event_addButtonActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void tabelaContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaContratosMouseClicked
        // TODO add your handling code here:
        deleteButton1.setEnabled(true);
        editButton1.setEnabled(true);
        int linha=tabelaContratos.getSelectedRow();
        nomeCampo1.setText(tabelaUsuarios.getValueAt(linha, 1).toString());
        idContratoCampo.setText(tabelaUsuarios.getValueAt(linha, 0).toString());
    }//GEN-LAST:event_tabelaContratosMouseClicked

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        // TODO add your handling code here:
        //JDIALOG PARA FECHAMENTO DE CONTRATO
        //IMPORTANTE

    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void editButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButton1ActionPerformed
        // TODO add your handling code here:
        //JDIALOG PARA EDITAR CONTRATO EXISTENTE
        new EditarContratos(null, true).setVisible(true);
        
    }//GEN-LAST:event_editButton1ActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        // TODO add your handling code here:
        //JDIALOG PARA SELECIONAR HÓSPEDE E ABRIR CONTRATO
        new EditarHóspede(null, true, 0).setVisible(true);
    }//GEN-LAST:event_addButton1ActionPerformed

    private void jScrollPane2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseEntered
        // TODO add your handling code here:
        //preencher1();
    }//GEN-LAST:event_jScrollPane2MouseEntered

    private void jScrollPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseEntered
        // TODO add your handling code here:
        //preencher();
    }//GEN-LAST:event_jScrollPane1MouseEntered

    private void abertoToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abertoToggleActionPerformed
        // TODO add your handling code here:
        preencher1();
    }//GEN-LAST:event_abertoToggleActionPerformed

    private void fechadoToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechadoToggleActionPerformed
        // TODO add your handling code here:
        preencher1();
    }//GEN-LAST:event_fechadoToggleActionPerformed

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButton2ActionPerformed

    private void tabelaServiçosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaServiçosMouseClicked
        // TODO add your handling code here:
        deleteButton2.setEnabled(true);
        editButton2.setEnabled(true);
        int linha=tabelaServiços.getSelectedRow();
        nomeCampo2.setText(tabelaServiços.getValueAt(linha, 1).toString());
        idContratoCampo1.setText(tabelaServiços.getValueAt(linha, 0).toString());
    }//GEN-LAST:event_tabelaServiçosMouseClicked

    private void jScrollPane3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseEntered

    private void deleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButton2ActionPerformed

    private void editButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButton2ActionPerformed

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicial dialog = new Inicial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenu AjudaMenu;
    private javax.swing.JMenu ArquivoMenu;
    private javax.swing.JPanel ContratosPanel;
    private javax.swing.JMenu ExibirMenu;
    private javax.swing.JPanel HóspedesPanel;
    private javax.swing.JPanel QuartosPanel;
    private javax.swing.JPanel ServiçosPanel;
    private javax.swing.JToggleButton abertoToggle;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addButton2;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JButton deleteButton2;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editButton1;
    private javax.swing.JButton editButton2;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JButton exitButton2;
    private javax.swing.JToggleButton fechadoToggle;
    private javax.swing.JLabel idCampo;
    private javax.swing.JLabel idContratoCampo;
    private javax.swing.JLabel idContratoCampo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JTextField nomeCampo1;
    private javax.swing.JTextField nomeCampo2;
    private javax.swing.JTable tabelaContratos;
    private javax.swing.JTable tabelaServiços;
    private javax.swing.JTable tabelaUsuarios;
    // End of variables declaration//GEN-END:variables
}
